はじめてのPR作成
shinonome-inc/backend-final-assignment-shota pull request #1
Opened 2024-04-04 07:38 UTC by shou-hatu

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-04-26 17:58 UTC, Shiota620 requested changes

2024-04-26 17:58 UTC, Shiota620 commented on .vscode/settings.json
> +    "source.organizeImports": "explicit"
この設定を変更した意図は何ですか。

2024-04-26 18:16 UTC, Shiota620 commented on accounts/models.py
不要なコメントは削除することを推奨します。
具体的には、1行目から7行目は不要と判断します。

2024-04-27 04:22 UTC, Shiota620 commented
これで一次レビューは終了です。お疲れ様でした。
二次レビューよろしくお願い致します。

2024-04-27 16:27 UTC, YOSIJUKI commented
お疲れ様です、とてもよく書けていると思います！
一点だけ、tweets/tests.pyのTestHomeViewの記述をお願いします！

2024-04-27 16:33 UTC, YOSIJUKI commented
すいません、追加でもう一点！
django-debug-toolbarを設定すると、パフォーマンスとデバッグに役立ちます。
以下の実装例を参考に記述してみてください！

# requirements.txtに以下を追記
django-debug-toolbar

# mysite/settings.py (見分けやすいように一番下の行に記述すると良い)

# テスト実行する際はここをFalseにすればOK。従って全てコメントアウトする必要なし
SQL_DEBUG = True 

if SQL_DEBUG:

    def show_toolbar(request):
        return True

    INSTALLED_APPS += ("debug_toolbar",)
    MIDDLEWARE += ("debug_toolbar.middleware.DebugToolbarMiddleware",)
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
    }

# myiste/urls.py

from django.conf import settings

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

2024-04-27 16:40 UTC, YOSIJUKI commented
すいません、追加でもう一点！
django-debug-toolbarを設定するとパフォーマンスとデバッグに役立ちます。
以下の実装例を参考に記述してみてください。

・requirements.txtに以下を追記
`django-debug-toolbar
`

・mysite/settings.py (見分けやすいように一番下の行に記述すると良い)
```
# テスト実行する際はここをFalseにすればOK。従って全てコメントアウトする必要なし
SQL_DEBUG = True 

if SQL_DEBUG:

    def show_toolbar(request):
        return True

    INSTALLED_APPS += ("debug_toolbar",)
    MIDDLEWARE += ("debug_toolbar.middleware.DebugToolbarMiddleware",)
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
    }

```

・myiste/urls.py

```
from django.conf import settings

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
```

2024-04-28 15:50 UTC, merged